FROM cgr.dev/chainguard/wolfi-base:latest

RUN apk add --no-cache \
    bash \
    coreutils \
    cmake \
    ninja \
    pkgconf \
    git \
    cargo \
    rust \
    gcc \
    g++ \
    qt6-qtbase-dev \
    qt6-qtdeclarative-dev \
    qt6-qtquickcontrols2-dev

WORKDIR /workspace

CMD ["/bin/sh"]
